"""
GitTool — Creates a git branch, commits the fixed file, and writes a PR summary.
Falls back to simulation if Git is not installed.
"""

import os
import subprocess
from datetime import datetime
from pydantic import BaseModel, Field
from crewai.tools import BaseTool

OUTPUT_DIR = os.path.join(os.path.dirname(__file__), "..", "output")
PROJECT_ROOT = os.path.join(os.path.dirname(__file__), "..")


def _git_available() -> bool:
    """Check if Git CLI is available."""
    try:
        subprocess.run(["git", "--version"], capture_output=True, check=True)
        return True
    except (FileNotFoundError, subprocess.CalledProcessError):
        return False


class GitToolSchema(BaseModel):
    ticket_id: str = Field(..., description="The Jira ticket ID, e.g. 'JIRA-101'")
    filename: str = Field(..., description="The fixed filename, e.g. 'fixed_login.py'")
    summary: str = Field(..., description="Short description of the changes made")


class GitTool(BaseTool):
    name: str = "git_commit"
    description: str = (
        "Creates a Git branch named 'fix/<ticket_id>', commits the fixed file, "
        "and writes a PR summary markdown in output/pr_summary.md. "
        "Pass 'ticket_id' (e.g. 'JIRA-101'), 'filename' (e.g. 'fixed_login.py'), "
        "and 'summary' (a short description of the changes)."
    )
    args_schema: type[BaseModel] = GitToolSchema

    def _run_git(self, args: list[str], cwd: str, check: bool = True) -> subprocess.CompletedProcess:
        return subprocess.run(args, cwd=cwd, capture_output=True, text=True, check=check)

    def _normalize_filename(self, filename: str) -> str:
        normalized = filename.strip().replace("\\", "/")
        if normalized.startswith("output/"):
            normalized = normalized[len("output/") :]
        normalized = os.path.normpath(normalized).replace("\\", "/")
        if not normalized or normalized in (".", "..") or normalized.startswith("../"):
            raise ValueError("Invalid filename")
        return normalized

    def _run(self, ticket_id: str, filename: str, summary: str, **kwargs) -> str:
        branch_name = f"fix/{ticket_id}"
        os.makedirs(OUTPUT_DIR, exist_ok=True)

        try:
            safe_filename = self._normalize_filename(filename)
        except ValueError:
            return f"ERROR: Invalid filename '{filename}'"

        # Write PR summary markdown
        pr_content = (
            f"# Pull Request — {ticket_id}\n\n"
            f"**Branch:** `{branch_name}`\n\n"
            f"## Changes\n\n{summary}\n\n"
            f"## Files Modified\n\n- `output/{safe_filename}`\n\n"
            f"## Test Steps\n\n"
            f"1. Review the fixed code in `output/{safe_filename}`\n"
            f"2. Run existing unit tests\n"
            f"3. Verify the bug described in {ticket_id} is resolved\n\n"
            f"---\n\n"
            f"*Auto-generated by Jira Solver Crew on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}*\n"
        )
        pr_path = os.path.join(OUTPUT_DIR, "pr_summary.md")
        with open(pr_path, "w", encoding="utf-8") as f:
            f.write(pr_content)

        if _git_available():
            try:
                cwd = os.path.abspath(PROJECT_ROOT)
                fixed_rel_path = f"output/{safe_filename}"

                branch_check = self._run_git(["git", "rev-parse", "--verify", branch_name], cwd=cwd, check=False)
                if branch_check.returncode == 0:
                    self._run_git(["git", "checkout", branch_name], cwd=cwd, check=True)
                else:
                    self._run_git(["git", "checkout", "-b", branch_name], cwd=cwd, check=True)

                self._run_git(["git", "add", fixed_rel_path, "output/pr_summary.md"], cwd=cwd, check=True)
                commit_result = self._run_git(
                    ["git", "commit", "-m", f"fix({ticket_id}): {summary}"],
                    cwd=cwd,
                    check=False,
                )

                if commit_result.returncode != 0:
                    commit_text = (commit_result.stderr or commit_result.stdout or "").strip()
                    if "nothing to commit" in commit_text.lower():
                        return (
                            f"SUCCESS: Branch '{branch_name}' ready; no new commit needed. "
                            "pr_summary.md updated."
                        )
                    return f"ERROR: Git commit failed on branch '{branch_name}': {commit_text}"

                return (
                    f"SUCCESS: Created branch '{branch_name}', committed "
                    f"output/{safe_filename}, and wrote pr_summary.md"
                )
            except Exception as e:
                return f"GIT_FALLBACK: Git commands failed ({e}). PR summary still written."
        else:
            return (
                f"GIT_FALLBACK: Git not installed. Simulated branch '{branch_name}'. "
                f"PR summary written to output/pr_summary.md"
            )
